#!/usr/bin/bash
# AWS连接信息，不定义则使用环境变量，定义则使用如下定义值
export AWS_ACCESS_KEY_ID=AKIATETRFRPDKSP5G7FT
export AWS_SECRET_ACCESS_KEY=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
export AWS_DEFAULT_REGION=ap-east-1
export EKS_CLUSTER=jack-cluster

# EFS文件系统的<file_system_id>
file_system_id=fs-b7225f7a

# busybox镜像地址
busybox_image=216059448262.dkr.ecr.ap-east-1.amazonaws.com/devops/centos:7

# namespace名称
namespace=devops

