#该文件存放通用公共变量 

# 指镜像参数
image:
  repository: null
  pullPolicy: Always
  # pullPolicy: IfNotPresent

# 匹配节点
nodeSelector: {}

# 卷挂载
volumeMounts_global:
 - name: logs
   mountPath: /logs
   emptyDir: "{}"

# 默认端口
service:
  type: ClusterIP
ports:
  - name: http
    protocol: TCP
    targetPort: 18081
    port: 18081

# configmap环境变量
configMap_env: "false"

# configmap配置文件
configMap_conf: "false"