apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appname }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appname }}
    service: {{ .Values.appname }}
spec:
  type: {{ .Values.service.type }}
  ports:
{{- $serviceType := .Values.service.type -}}
{{- range .Values.ports }}
    {{- with . }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      targetPort: {{ .targetPort }}
      port: {{ .port }}
      {{- if (and (eq $serviceType "NodePort") (not (empty .nodePort))) }}
      nodePort: {{ .nodePort }}
      {{- end }}
    {{- end }}
{{- end}}
  selector:
    app: {{ .Values.appname }}
