apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appname }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appname }}
    service: {{ .Values.appname }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http-httpapi
      protocol: TCP
      port: 1001
      targetPort: 1001
    - name: tcp-httpapi
      protocol: TCP
      port: 9999
      targetPort: 9999
    - name: grpc-grpc-demo
      protocol: TCP
      port: 10000
      targetPort: 10000

  selector:
    app: {{ .Values.appname }}
