{{- if default "" .Values.externalUrl }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "gitlab-ce.fullname" . }}
  labels:
    app: {{ template "gitlab-ce.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    matchLabels:
       app: {{ template "gitlab-ce.fullname" . }}
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  serviceName: {{ template "gitlab-ce.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "gitlab-ce.fullname" . }}
    spec:
      containers:
      # gitlab 相关参数，postgresql、redis
      - env:
        - name: GITLAB_ROOT_PASSWORD
          value: {{ .Values.gitlabRootPassword }}
        - name: EXTERNAL_URL
          value: {{ default "" .Values.externalUrl | quote }}
        - name: GITLAB_OMNIBUS_CONFIG
          value: |
            {{- range .Values.gitlabConfig }}
            {{. }}
            {{- end }}
        name: {{ template "gitlab-ce.fullname" . }}
        image: {{ .Values.image }}
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        ports:
        - name: ssh
          containerPort: 22
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.livenessPort }}
          # This pod takes a very long time to start up. Be cautious when
          # lowering this value to avoid Pod death during startup.
          initialDelaySeconds: 300
          timeoutSeconds: 5
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.readinessPort }}
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
#        - name: timezone
#          mountPath: /etc/timezone
#        - name: localtime
#          mountPath: /etc/localtime
        {{- if .Values.persistence.enabled }}
        {{- range .Values.persistence.mountInfo }}
        - name: {{ .name }}
          mountPath: {{ .mountPath }}
          subPath: {{ .subPath }}
        {{- end }}
        {{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
      volumes:
#      - name: timezone
#        hostPath:
#          path: /etc/timezone
#          type: File
#      - name: localtime
#        hostPath:
#          path: /usr/share/zoneinfo/Asia/Shanghai
#          type: File
      {{- if .Values.persistence.enabled }}
      - name: gitlab-pvc
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.pvcName }}
      {{- end }}
{{ else }}
{{ end }}
