#!/usr/bin/bash
# AWS连接信息，不定义则使用环境变量，定义则使用如下定义值
export AWS_ACCESS_KEY_ID=AKIATETRFRPDKSP5G7FT
export AWS_SECRET_ACCESS_KEY=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
export AWS_DEFAULT_REGION=ap-east-1
export EKS_CLUSTER=jack-cluster
export AWS_ACCOUNT_ID=216059448262

# S3桶名称，用于存放Jenkins插件包
s3_bucket_name=jack-test-devops

# EFS文件系统的<file_system_id>
file_system_id=fs-b7225f7a

# busybox镜像地址
busybox_image=216059448262.dkr.ecr.ap-east-1.amazonaws.com/devops/busybox:1.32

# jenkins镜像地址
jenkins_image=216059448262.dkr.ecr.ap-east-1.amazonaws.com/devops/jenkins:2.277.3-lts

# jenkins插件下载地址
jenkins_plugins_url=https://jack-test-devops.s3.ap-east-1.amazonaws.com/jenkins-3.3.9-plugins.tar.gz

# jenki部署到的kubernetes namespace名称
namespace=devops

# jenkins的资源限制
requests_cpu=500m
requests_mem=1024Mi
limits_cpu=1000m
limits_mem=2048Mi

# jenkins的javaopts参数
jenkins_javaopts="-Xms128m -Xmx1024m "
