name: gitlab-ce
deprecated: false
version: 1.0.0
appVersion: 12.10.14
description: GitLab Community Edition
keywords:
- git
- ci
- deploy
- issue tracker
- code review
- wiki
home: https://about.gitlab.com
sources:
- https://hub.docker.com/r/gitlab/gitlab-ce/
- https://docs.gitlab.com/omnibus/
icon: https://gitlab.com/uploads/group/avatar/6543/gitlab-logo-square.png
